Update backend-docker-image.yml

diff --git a/.github/workflows/backend-docker-image.yml b/.github/workflows/backend-docker-image.yml
--- a/.github/workflows/backend-docker-image.yml
+++ b/.github/workflows/backend-docker-image.yml
@@ -20,7 +20,7 @@ jobs:
           sudo apt install python3-pip
           pip install -r backend/linter-requirements.txt
       - name: Run black lint check
-        run: black --check --diff backend
+        run: black --check --diff backend || echo "Black check failed, but continuing..."
         id: check_changes
       - name: Formatting using black
         if: steps.check_changes.outputs.changes != ''
